env:
    - CFLAGS=-Werror

before_install:
    - fusermount -V

install:
    - sudo apt-get install libfuse-dev

before_script:
    - mkdir mount
    - sudo chmod a+rw /dev/loop0
    - dd if=/dev/zero bs=512 count=2048 of=disk
    - losetup /dev/loop0 disk

script:
    - make
    - ./lfs --format /dev/loop0
    - ./lfs /dev/loop0 mount
    - cd mount && ls
    - cp -r ../littlefs .
    - cd littlefs && ls
    - make -B test_dirs
    - make -B test_files

deploy:
    # Let before_deploy take over
    provider: script
    script: 'true'
    on:
        branch: master

before_deploy:
    - cd $TRAVIS_BUILD_DIR
    # Find version defined in lfs.h
    - LFS_VERSION=$(grep -ox '#define LFS_VERSION .*' littlefs/lfs.h | cut -d ' ' -f3)
    - LFS_VERSION_MAJOR=$((0xffff & ($LFS_VERSION >> 16)))
    - LFS_VERSION_MINOR=$((0xffff & ($LFS_VERSION >>  0)))
    # Grab latests patch from repo tags, default to 0
    - LFS_VERSION_PATCH=$(curl -f -u "$GEKY_BOT_RELEASES"
            https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs
            | jq 'map(.ref | match(
                "refs/tags/v'"$LFS_VERSION_MAJOR"'\\.'"$LFS_VERSION_MINOR"'\\.(.*)$")
                .captures[].string | tonumber + 1) | max // 0')
    # We have our new version
    - LFS_VERSION="v$LFS_VERSION_MAJOR.$LFS_VERSION_MINOR.$LFS_VERSION_PATCH"
    - echo "VERSION $LFS_VERSION"
    - |
      # Check that we're the most recent commit
      CURRENT_COMMIT=$(curl -f -u "$GEKY_BOT_RELEASES" \
            https://api.github.com/repos/$TRAVIS_REPO_SLUG/commits/master \
            | jq -re '.sha')
      if [ "$TRAVIS_COMMIT" == "$CURRENT_COMMIT" ]
      then
        # Build release notes
        PREV=$(git tag --sort=-v:refname -l "v*" | head -1)
        if [ ! -z "$PREV" ]
        then
            echo "PREV $PREV"
            CHANGES=$'### Changes\n\n'$( \
                git log --oneline $PREV.. --grep='^Merge' --invert-grep)
            printf "CHANGES\n%s\n\n" "$CHANGES"
        fi
        # Create the release
        curl -f -u "$GEKY_BOT_RELEASES" -X POST \
            https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases \
            -d "{
                \"tag_name\": \"$LFS_VERSION\",
                \"target_commitish\": \"$TRAVIS_COMMIT\",
                \"name\": \"${LFS_VERSION%.0}\",
                \"body\": $(jq -sR '.' <<< "$CHANGES")
            }"
      fi

